name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  commit_message_based_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/commit-message-based-labels@86faa4da01e28a7dbd9cd6f7da848d9f163a7fc8
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
