name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@86faa4da01e28a7dbd9cd6f7da848d9f163a7fc8
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
